# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

class SaveWindow(QDialog):
    def __init__(self):
        super().__init__()
        self.top = 200
        self.left = 200
        self.width = 600
        self.height = 500
        self.initUI()

    def initUI(self):
        self.setWindowTitle("Password Manager")
        self.label = QLabel(self)
        self.label.setGeometry(QRect(110, 70, 371, 81))
        font = QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setText("Type in the information below")

        self.formLayoutWidget = QWidget(self)
        self.formLayoutWidget.setGeometry(QRect(150, 150, 291, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        self.websiteLabel = QLabel(self.formLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.websiteLabel.setFont(font)
        self.websiteLabel.setObjectName("websiteLabel")
        self.websiteLabel.setText("Website:")

        self.websiteLineEdit = QLineEdit(self.formLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.websiteLineEdit.setFont(font)
        self.websiteLineEdit.setObjectName("websiteLineEdit")
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.websiteLabel)
        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.websiteLineEdit)

        self.usernameLabel = QLabel(self.formLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameLabel.setText("Username:")

        self.usernameLineEdit = QLineEdit(self.formLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.usernameLabel)
        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.usernameLineEdit)

        self.passwordLabel = QLabel(self.formLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordLabel.setText("Password:")
        self.passwordLineEdit = QLineEdit(self.formLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.passwordLabel)
        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.passwordLineEdit)

        self.pushButton = QPushButton(self)
        self.pushButton.setGeometry(QRect(170, 280, 241, 51))
        font = QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("Save")

    def to_main_window(self):
        widget.setCurrentIndex(widget.currentIndex()-1)


class Window(QMainWindow):
    def __init__(self):
        super(Window, self).__init__()
        self.top = 200
        self.left = 200
        self.width = 600
        self.height = 500
        self.initUI()

    def initUI(self):
        self.setWindowTitle("Password Manager")
        self.setGeometry(self.top, self.left, self.width, self.height)

        self.saveButton = QPushButton(self)
        self.saveButton.setGeometry(QtCore.QRect(90, 230, 200, 60))
        self.saveButton.setObjectName("saveButton")
        self.saveButton.setText("Save")
        self.saveButton.clicked.connect(self.to_save_window)

        self.loadButton = QPushButton(self)
        self.loadButton.setGeometry(QtCore.QRect(310, 230, 200, 60))
        self.loadButton.setObjectName("loadButton")
        self.loadButton.setText("Load")

        self.label = QLabel(self)
        self.label.setGeometry(QRect(90, 140, 421, 71))
        font = QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(Qt.LeftToRight)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setText("Welcome to Password Manager!")

    def to_save_window(self):
        widget.setCurrentIndex(widget.currentIndex()+1)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    widget = QStackedWidget()
    mainwindow = Window()
    savewindow = SaveWindow()

    widget.addWidget(mainwindow)
    widget.addWidget(savewindow)
    widget.setFixedWidth(600)
    widget.setFixedHeight(500)

    widget.show()
    sys.exit(app.exec_())
